name: What-If Data Validation

on:
  push:
    branches:
      - master 
    
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - name: Execute tests
          uses: joonvena/robotframework-docker-action@v0.1
          env:
            BROWSER: chrome
            ROBOT_TESTS_DIR: ${{ github.workspace }}/UI Automation Bucket/Tests/DimensionTests.robot
            ROBOT_REPORTS_DIR: ${{ github.workspace }}/reports
        - name: Upload test results
          uses: actions/upload-artifact@v1
          if: always()
          with:
            name: reports
            path: ${{ github.workspace }}/reports
