name: What-If Data Validation

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r What-If_Data_Validation/requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v -s --junitxml="report.xml" What-If_Data_Validation/test_what-if_data_validation.py
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: Test Results (Python ${{ matrix.python-version }})
          path: report.xml
  
  publish_unit_test:
      runs-on: ubuntu-latest
      needs: build
      if: success() || failure()
      steps:  
      - id: publish_unit_test        
        name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1
        with:
          files: artifacts/**/*.xml
          
#     - name: Test with pytest
#       run: |
#         pip install pytest
#         pytest -v -s --junitxml="report.xml" What-If_Data_Validation/test_what-if_data_validation.py
    
#     - name: Upload Test Results
#       if: always()
#       uses: actions/upload-artifact@v2
#       with:
#           name: Test Results (Python ${{ matrix.python-version }})
#           path: report.xml
  
#   publish-test-results:
#     name: "Publish Tests Results"
#     needs: build
#     runs-on: ubuntu-latest
#     if: always()

#     steps:
#       - name: Download Artifacts
#         uses: actions/download-artifact@v2
#         with:
#           path: artifacts

#       - name: Test Results
#         uses: EnricoMi/publish-unit-test-result-action@v1
#         with:
#           files: artifacts/**/*.xml
