name: What-If Data Validation

on:
  schedule:
    - cron: '0 0-23 * * *'
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r What-If_Data_Validation/requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v -s --junitxml="xml_report.xml" --html="html_report.html" What-If_Data_Validation/test_what-if_data_validation.py
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: test-report
          path: xml_report.xml
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: test-report
          path: html_report.html
  
  publish-test-results:
      runs-on: ubuntu-latest
      needs: build
      if: success() || failure()
      
      steps:
        - name: Download Artifacts
          uses: actions/download-artifact@v2
          with:
            path: artifacts

        - name: Test Results
          if: always()
          uses: EnricoMi/publish-unit-test-result-action@v1.25
          with:
            files: artifacts/test-report/xml_report.xml
