name: What-If Data Validation

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0-23 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r What-If_Data_Validation/requirements.txt
    - name: Test with pytest
      run: |
        pip install pytest
        pytest -v -s --html=report.html What-If_Data_Validation/test_what-if_data_validation.py
    
    - name: Upload Test Results
      if: always()
      uses: actions/upload-artifact@v2
      with:
          name: Test Results (Python ${{ matrix.python-version }})
          path: report.html
